repos:
- repo: local
  hooks:
  - id: pytest-check
      name: pytest-check
      entry: python -m pytest tests/unit/ -v
      language: system
      pass_filenames: false
      always_run: true
      stages: [commit]