version: '3.8'

services:
  # API FastAPI
  api:
    build: .
    container_name: trendpulse_api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:posgtgres123@postgres:5432/trendpulse
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - ENVIRONMENT=${ENVIRONMENT:-production}
      - GITHUB_PAGES_URL=${GITHUB_PAGES_URL}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - REDDIT_CLIENT_ID=${REDDIT_CLIENT_ID}
      - REDDIT_SECRET=${REDDIT_SECRET}
      - REDDIT_USERNAME=${REDDIT_USERNAME}
      - REDDIT_PASSWORD=${REDDIT_PASSWORD}
    volumes:
      - .:/app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    profiles:
      - production
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  # PostgreSQL
  postgres:
    image: postgres:15
    container_name: trendpulse_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=posgtgres123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=trendpulse
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Redis
  redis:
    image: redis:7.0
    container_name: trendpulse_redis
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    sysctls:
      net.core.somaxconn: 1024
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    restart: unless-stopped

  # Migrate
  migrate:
    build: .
    container_name: trendpulse_migrate
    command: >
      /bin/bash -c "
        echo 'Aguardando PostgreSQL...' &&
        sleep 10 &&
        cd /app && python -c 'from app.models import create_tables; create_tables()'
      "
    environment:
      - DATABASE_URL=postgresql://postgres:posgtgres123@postgres:5432/trendpulse
    volumes:
      - .:/app
    depends_on:
      postgres:
        condition: service_healthy

  # Worker
  worker:
    build: .
    container_name: trendpulse_worker
    command: celery -A app.tasks worker --loglevel=info
    environment:
      - DATABASE_URL=postgresql://postgres:posgtgres123@postgres:5432/trendpulse
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - REDDIT_CLIENT_ID=${REDDIT_CLIENT_ID}
      - REDDIT_SECRET=${REDDIT_SECRET}
      - REDDIT_USERNAME=${REDDIT_USERNAME}
      - REDDIT_PASSWORD=${REDDIT_PASSWORD}
    volumes:
      - .:/app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully

  # Beat
  beat:
    build: .
    container_name: trendpulse_beat
    command: celery -A app.tasks beat --loglevel=info
    environment:
      - DATABASE_URL=postgresql://postgres:posgtgres123@postgres:5432/trendpulse
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - .:/app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully

  # Flower
  flower:
    build: .
    container_name: trendpulse_flower
    command: celery -A app.tasks flower --port=5555 --db=/tmp/flower
    ports:
      - "5555:5555"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://postgres:posgtgres123@postgres:5432/trendpulse
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - FLOWER_DB=/tmp/flower
    depends_on:
      redis:
        condition: service_healthy

volumes:
  postgres_data:
  redis_data:
