services:
  # API FastAPI
  - type: web
    name: trendpulse-api
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    healthCheckPath: /api/status
    healthCheckTimeout: 30
    healthCheckInterval: 60
    buildCommand: bash ./pre_deploy_tests.sh
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: CELERY_BROKER_URL
        fromService:
          name: trendpulse-redis
          type: redis
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          name: trendpulse-redis
          type: redis
          property: connectionString
      - key: ENVIRONMENT
        value: production
      - key: GITHUB_PAGES_URL
        sync: false
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: SERVICE
        value: api
      - key: INSTALL_DEV_DEPS
        value: "true"

  # Celery Worker
  - type: worker
    name: trendpulse-worker
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: CELERY_BROKER_URL
        fromService:
          name: trendpulse-redis
          type: redis
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          name: trendpulse-redis
          type: redis
          property: connectionString
      - key: YOUTUBE_API_KEY
        sync: false
      - key: REDDIT_CLIENT_ID
        sync: false
      - key: REDDIT_SECRET
        sync: false
      - key: REDDIT_USERNAME
        sync: false
      - key: REDDIT_PASSWORD
        sync: false
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: SERVICE
        value: worker

  # Celery Beat
  - type: worker
    name: trendpulse-beat
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: CELERY_BROKER_URL
        fromService:
          name: trendpulse-redis
          type: redis
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          name: trendpulse-redis
          type: redis
          property: connectionString
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: SERVICE
        value: beat

  # Flower Dashboard
  - type: web
    name: trendpulse-flower
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: CELERY_BROKER_URL
        fromService:
          name: trendpulse-redis
          type: redis
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          name: trendpulse-redis
          type: redis
          property: connectionString
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: FLOWER_BASIC_AUTH
        sync: false
      - key: SERVICE
        value: flower

  # Redis
  - type: redis
    name: trendpulse-redis
    plan: starter
    maxmemoryPolicy: allkeys-lru
    ipAllowList: []
